name: Build and Test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    name: Test Solution Cases
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19.1
        uses: actions/setup-go@v1
        with:
          go-version: 1.19.1
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Test Solution
        run: make test
